FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
ARG PYTHON_VERSION=3.5.6
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates \
         libjpeg-dev \
         libpng-dev \
         nano

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

RUN /opt/conda/bin/conda create --name build -y python=${PYTHON_VERSION} numpy pyyaml scipy ipython mkl mkl-include ninja cython typing
RUN /opt/conda/bin/conda install --name build -y -c pytorch magma-cuda100

# This must be done before pip so that requirements.txt is available
WORKDIR /opt
ADD pytorch.tar.gz .
WORKDIR /opt/pytorch

RUN conda init bash 

COPY build.sh .
RUN chmod +x build.sh

ENTRYPOINT "/opt/pytorch/build.sh"
